### ISSUE TITLE
Information about Merchant Name and Merchant City

### ISSUE THREAD

**Issue by tong-odoo** [anhjean/vietqr#1]
Hello, I saw you mentioned about Merchant Name and Merchant City are mandatory fields on the QR code. However I am testing with the Vietnamese FC and found out without the fields, the banking app will automatically add the account name in the payment. If we add the fields, the account name will be empty in the payment.

May I ask do you know what will happen if we don't include Merchant Name and Merchant City in the QR code? Will it throw error if we use different QR service types other than `QRIBFTTA`? 

Thank you for your attention!

**Comment by anhjean** [comment]
As mentioned, Merchant Name and Merchant City are mandatory. But for VietQR with service code QRIBFTTA and QRIBFTTC the bank app don't check these fields. This field will be check for VietQR with service code QRPUSH and QRATM.
But  VietQR with service code QRPUSH and QRCASH are the standard and all bank app in developing to adapt these standard.

If you don't use the right service code (QRPUSH,QRPUSH,QRTBFTTA and QRIBFTTC), the app bank will show "Qr format" error

**Comment by tong-odoo** [comment]
@anhjean thank you the reply. In this case, may I ask if it is fine for me to always include the Merchant Name and Merchant City?

**Comment by anhjean** [comment]
yes, you can always include the Merchant Name and Merchant City
When you do the customer EMV QR for VN market on Odoo, please keep me in loop. I'm willing to help

**Comment by anhjean** [comment]
btw mr @tong-odoo , can i fork your module from odoo sass-16.3 to  odoo 16 ?

**Comment by tong-odoo** [comment]
@anhjean Thanks for the information. Sure I will keep you in loop! For the module fork, my only concern is when you do migration it will cause issue. Also you need to update the setting view back to odoo 16 style. 
Other than that, I am all good for you to fork the module to Odoo 16.

**Comment by tong-odoo** [comment]
Hello @anhjean, you could follow the PR in here. https://github.com/odoo/odoo/pull/127689
I haven't included the static QR code generation yet bcs I need to research a bit before adding it to all country. This one is a PR for dynamic QR code generation for now.

**Comment by anhjean** [comment]
@tong-odoo , Can you add my github name in the "description" section  of l10n_vn module 'manifest' files as a  VietQR advisor ? like following

"description": """
This is the module to manage the accounting chart, bank information for Vietnam in Odoo.
===========================================================================================
        
- This module applies to companies based in Vietnamese Accounting Standard (VAS) with Chart of account under Circular No. 200/2014/TT-BTC.
- Add Vietnamese bank information (like name, bic ..) as announced and yearly updated by State Bank of Viet Nam (https://sbv.gov.vn/webcenter/portal/en/home/sbv/paytreasury/bankidno).
- Add VietQR feature for invoice 
        
**Credits:**
    - General Solutions.
    - Trobz

**VietQR advisor**
    - Jean Nguyen - The Bean Family (https://github.com/anhjean/vietqr)
    """,

**Comment by tong-odoo** [comment]
Sure
